-- ============================================================
-- Tracker de Recomposición — Esquema Supabase (Postgres)
-- Ejecuta TODO este archivo en: Supabase > SQL Editor > New query > Run
-- ============================================================

-- ---------- TABLAS ----------
create table if not exists public.profiles (
  user_id       uuid primary key references auth.users(id) on delete cascade,
  height_m      numeric  default 1.75,
  start_weight  numeric,
  kcal_target   integer  default 2800,
  protein_target integer default 175,
  fat_target    integer  default 75,
  rate_min      numeric  default 0.15,
  rate_max      numeric  default 0.25,
  cut_threshold numeric  default 0.30,
  waist_alert   numeric  default 0.6,
  kcal_step     integer  default 150,
  updated_at    timestamptz default now()
);

create table if not exists public.foods (
  id            bigint generated by default as identity primary key,
  user_id       uuid references auth.users(id) on delete cascade, -- null = alimento global (semilla)
  name          text not null,
  category      text,
  kcal_100      numeric not null,
  protein_100   numeric not null,
  carbs_100     numeric not null,
  fat_100       numeric not null,
  unit_label    text default 'porción',
  grams_per_unit numeric default 100,
  note          text
);

create table if not exists public.food_log (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users(id) on delete cascade,
  log_date   date not null,
  meal       text not null,           -- Desayuno | Comida | Snack | Cena
  food_id    bigint references public.foods(id) on delete set null,
  food_name  text,                    -- copia del nombre por si el alimento cambia
  quantity   numeric not null,
  unit       text not null default 'g', -- 'g' | 'porcion'
  grams      numeric,
  kcal       numeric,
  protein    numeric,
  carbs      numeric,
  fat        numeric,
  created_at timestamptz default now()
);

create table if not exists public.weight_log (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users(id) on delete cascade,
  log_date   date not null,
  weight_kg  numeric,
  waist_cm   numeric,
  created_at timestamptz default now(),
  unique (user_id, log_date)
);

create index if not exists idx_food_log_user_date   on public.food_log (user_id, log_date);
create index if not exists idx_weight_log_user_date on public.weight_log (user_id, log_date);
create index if not exists idx_foods_user           on public.foods (user_id);

-- ---------- ROW LEVEL SECURITY ----------
alter table public.profiles   enable row level security;
alter table public.foods      enable row level security;
alter table public.food_log   enable row level security;
alter table public.weight_log enable row level security;

-- profiles: cada quien ve/edita SOLO lo suyo
create policy "profiles_select_own" on public.profiles for select using (auth.uid() = user_id);
create policy "profiles_insert_own" on public.profiles for insert with check (auth.uid() = user_id);
create policy "profiles_update_own" on public.profiles for update using (auth.uid() = user_id);

-- foods: todos leen la semilla global (user_id null) + los suyos; escriben solo los suyos
create policy "foods_select"      on public.foods for select using (user_id is null or auth.uid() = user_id);
create policy "foods_insert_own"  on public.foods for insert with check (auth.uid() = user_id);
create policy "foods_update_own"  on public.foods for update using (auth.uid() = user_id);
create policy "foods_delete_own"  on public.foods for delete using (auth.uid() = user_id);

-- food_log / weight_log: acceso total SOLO a lo propio
create policy "food_log_own"   on public.food_log   for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "weight_log_own" on public.weight_log for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------- SEMILLA DE ALIMENTOS (global, user_id = null) ----------
-- Fuente de valores por 100 g: USDA FoodData Central (referencia estándar).
insert into public.foods (name, category, kcal_100, protein_100, carbs_100, fat_100, unit_label, grams_per_unit, note) values
  ('Aceite de oliva', 'Grasa', 884, 0, 0, 100, '1 cda', 14, null),
  ('Aguacate', 'Grasa', 160, 2, 8.5, 14.7, '1/2 pieza', 68, null),
  ('Almendras', 'Grasa', 579, 21, 22, 50, 'puño', 20, null),
  ('Arroz blanco (cocido)', 'Cereal', 130, 2.7, 28, 0.3, '1 taza', 158, 'Cocido'),
  ('Atún en agua (drenado)', 'Proteína', 116, 26, 0, 1, '1/2 lata', 80, null),
  ('Avena hojuelas (cruda)', 'Cereal', 379, 13, 67, 6.5, 'porción', 40, 'En seco'),
  ('Brócoli', 'Verdura', 34, 2.8, 7, 0.4, '1 taza', 90, null),
  ('Camote (cocido)', 'Tubérculo', 90, 2, 21, 0.1, '1 mediano', 150, null),
  ('Cebolla', 'Verdura', 40, 1.1, 9.3, 0.1, '1/4 pieza', 40, null),
  ('Clara de huevo', 'Proteína', 52, 10.9, 0.7, 0.2, '1 clara', 33, null),
  ('Coliflor', 'Verdura', 25, 1.9, 5, 0.3, '1 taza', 100, null),
  ('Crema de cacahuate', 'Grasa', 588, 25, 20, 50, '1 cda', 16, 'Verifica etiqueta'),
  ('Elote en grano', 'Verdura', 86, 3.2, 19, 1.2, '1/2 taza', 82, null),
  ('Espinaca', 'Verdura', 23, 2.9, 3.6, 0.4, '1 taza', 30, null),
  ('Fresa', 'Fruta', 32, 0.7, 7.7, 0.3, '1 taza', 150, null),
  ('Frijoles (cocidos)', 'Leguminosa', 132, 8.9, 24, 0.5, '1/2 taza', 90, 'Cocidos'),
  ('Huevo entero', 'Proteína', 143, 12.6, 0.7, 9.5, '1 pieza', 50, null),
  ('Jamón pechuga de pavo', 'Proteína', 104, 17, 3, 2.5, '1 rebanada', 28, 'Verifica etiqueta'),
  ('Jitomate', 'Verdura', 18, 0.9, 3.9, 0.2, '1 pieza', 123, null),
  ('Leche entera', 'Lácteo', 61, 3.2, 4.8, 3.3, '1 vaso 240ml', 245, 'por 100 ml'),
  ('Leche semidescremada', 'Lácteo', 50, 3.4, 5, 1.9, '1 vaso 240ml', 245, 'por 100 ml'),
  ('Lentejas (cocidas)', 'Leguminosa', 116, 9, 20, 0.4, '1/2 taza', 100, 'Cocidas'),
  ('Manzana', 'Fruta', 52, 0.3, 14, 0.2, '1 mediana', 180, null),
  ('Miel', 'Otro', 304, 0.3, 82, 0, '1 cda', 21, null),
  ('Nopal (cocido)', 'Verdura', 16, 1.3, 3.3, 0.1, '1 taza', 150, null),
  ('Nueces', 'Grasa', 654, 15, 14, 65, 'puño', 20, null),
  ('Pan integral', 'Cereal', 247, 13, 41, 3.4, '1 rebanada', 28, null),
  ('Papa (cocida)', 'Tubérculo', 87, 1.9, 20, 0.1, '1 mediana', 150, null),
  ('Papaya', 'Fruta', 43, 0.5, 11, 0.3, '1 taza', 145, null),
  ('Pasta (cocida)', 'Cereal', 158, 5.8, 31, 0.9, '1 taza', 140, 'Cocida'),
  ('Plátano', 'Fruta', 89, 1.1, 23, 0.3, '1 mediano', 118, null),
  ('Pollo pechuga (cocida)', 'Proteína', 165, 31, 0, 3.6, 'filete', 150, 'Cocida'),
  ('Queso manchego', 'Lácteo', 350, 24, 2, 28, 'rebanada', 30, 'Verifica etiqueta'),
  ('Queso Oaxaca', 'Lácteo', 350, 25, 3, 27, 'porción', 30, null),
  ('Queso panela', 'Lácteo', 215, 18, 3, 15, 'rebanada', 40, null),
  ('Requesón', 'Lácteo', 130, 11, 3, 8, 'porción', 60, null),
  ('Res molida 90/10 (cocida)', 'Proteína', 217, 26, 0, 12, 'porción', 120, 'Cocida'),
  ('Salmón (cocido)', 'Proteína', 206, 22, 0, 13, 'porción', 150, null),
  ('Tortilla de harina', 'Cereal', 310, 8, 50, 8, '1 tortilla', 40, 'Verifica etiqueta'),
  ('Tortilla de maíz', 'Cereal', 218, 5.7, 45, 2.8, '1 tortilla', 28, null),
  ('Tostada horneada', 'Cereal', 434, 8, 74, 11, '1 pieza', 12, 'Verifica etiqueta'),
  ('Whey Gold Standard (choc)', 'Suplemento', 387, 77, 10, 5, '1 scoop', 31, 'Verifica etiqueta'),
  ('Yogurt griego natural 0%', 'Lácteo', 59, 10, 3.6, 0.4, '1 vaso', 170, 'Sin azúcar'),
  ('Zanahoria', 'Verdura', 41, 0.9, 10, 0.2, '1 pieza', 60, null),
  ('Melón', 'Fruta', 34, 0.8, 8.2, 0.2, '1 taza', 160, 'Melón chino'),
  ('Mix de Verduras', 'Verdura', 38, 2, 7.6, 0, '1 taza', 140, 'NutriVerde (congelado)');
